Разметка страницы формы
htmlacademy-adaptive/1644719-cat-energy-22 pull request #3
Opened 2021-04-02 15:53 UTC by shnore

2021-04-02 18:20 UTC, sealeye commented on source/form.html
> +            <label class="input-main-list__item--label" for="name">ИМЯ:*</label>
Неверно использован модификатор. Модификатор это дополнительный класс к элементу. Здесь должен быть класс элемента. 
Ниже по коду ошибка повторяется.

2021-04-02 18:20 UTC, sealeye commented on source/form.html
> +            <input class="input-main-list__item--input" type="text" name="weight" id="weight" placeholder="7" value="7">
Тут тип number, как и у поля ниже.

2021-04-02 18:21 UTC, sealeye commented on source/form.html
> +            <input class="input-main-list__item--input" type="text" name="age" id="age" placeholder="7" value="7">
Все инпуты и все лейблы на странице выглядят одинаково, а значит должны иметь один и тот же класс, а не разные.

2021-04-02 18:22 UTC, sealeye commented on source/form.html
> +            <input class="visually-hidden input-radio" type="radio" name="program_type" id="weight_loss"
Почему input-radio это блок? 
Мы разве можем вынести его за форму?

2021-04-02 18:22 UTC, sealeye commented on source/form.html
> +            <label for="weight_loss">похудение</label>
У всех тегов должны быть классы.

2021-04-02 18:22 UTC, sealeye commented on source/form.html
> +        <h2 class="page-form-filter-contacts__header">Контактные данные
Почему это заголовок, а не legend?

2021-04-02 18:23 UTC, sealeye commented on source/form.html
> +            <div class="input-fields-list__item--icon"></div>
Для иконки не нужен отдельный пустой див, это будет либо псевдоэлемент, либо онлайновый свг.

2021-04-02 18:24 UTC, sealeye commented on source/form.html
> +      <fieldset class="page-form-filter-contacts">
Почему у тебя какие-то филдсеты это блоки, а какие-то элементы? 
Филдсет мы вообще вне формы вынести не можем, потому что это будет невалидно и несемантично.

2021-04-02 18:26 UTC, sealeye requested changes
В разметке формы наблюдается какое-то неединообразие разметки, одинаковые элементы сделаны разными классами, неправильно использованы модификаторы, отсутствует логика в нейминге похожих элементов. Тут есть над чем поработать.

2021-04-05 13:59 UTC, shnore commented on source/form.html
> +      <fieldset class="page-form-filter-contacts">
ошибочно думала, что в элементы нельзя вставлять другие элементы того же блока
пробую исправить, в данном случае описка, теперь это элемент блока form

2021-04-05 13:59 UTC, shnore commented on source/form.html
> +            <div class="input-fields-list__item--icon"></div>
добавила инлайновый свг

2021-04-05 13:59 UTC, shnore commented on source/form.html
> +        <h2 class="page-form-filter-contacts__header">Контактные данные
в макете было похоже на заголовок, исправила на legend

2021-04-05 13:59 UTC, shnore commented on source/form.html
> +            <label for="weight_loss">похудение</label>
вроде теперь у всех

2021-04-05 14:00 UTC, shnore commented on source/form.html
> +            <input class="visually-hidden input-radio" type="radio" name="program_type" id="weight_loss"
из материалов курса не совсем поняла где использовать блок, а где элемент, в этом еще путаюсь
сейчас изменила название класса radio-list на модификатор блока input

2021-04-05 14:00 UTC, shnore commented on source/form.html
> +            <input class="input-main-list__item--input" type="text" name="age" id="age" placeholder="7" value="7">
вынесла label и input в отдельные классы

2021-04-05 14:00 UTC, shnore commented on source/form.html
> +            <input class="input-main-list__item--input" type="text" name="weight" id="weight" placeholder="7" value="7">
исправила тип у инпутов на type="number" у этих двух элементов

2021-04-05 14:00 UTC, shnore commented on source/form.html
> +            <label class="input-main-list__item--label" for="name">ИМЯ:*</label>
убрала модификаторы из однотипных элементов

2021-04-05 19:44 UTC, sealeye commented on source/form.html
> +            <input class="visually-hidden input--radio" type="radio" name="program_type" id="weight_loss"
Нельзя использовать модификатор как единственный класс. Модификатор это всегда зависимый класс и рядом с ним должен быть класс от которого модификатор образуется.

2021-04-05 19:45 UTC, sealeye commented on source/form.html
> +            <label class="label" for="weight_loss">похудение</label>
класс label не может быть блоком по БЭМ, потому что мы не можем вынести его на любую страницу или поместить в подвал без потери контекста, потому что label всегда привязан к инпуту, он зависим от него.

2021-04-05 19:47 UTC, sealeye commented on source/form.html
> +            <input class="visually-hidden input-radio" type="radio" name="program_type" id="weight_loss"
Блок - это самостоятельный элемент, который мы можем переиспользовать на другой странице или в любом месте сайта без потери контекста. 
Элемент - зависимая от блока часть разметки, которую вне блока использовать нельзя.

2021-04-05 20:38 UTC, shnore commented on source/form.html
> +            <input class="visually-hidden input--radio" type="radio" name="program_type" id="weight_loss"
модификатор образуется от input, добавила рядом

2021-04-05 20:40 UTC, shnore commented on source/form.html
> +            <label class="label" for="weight_loss">похудение</label>
спасибо!
жаль, что эта мысль не пришла в нужный момент)
теперь это form__label
если я правильно тебя поняла

2021-04-06 20:24 UTC, merged